import 'package:untitled1/Models/Error/error_model.dart';

List<ErrorModel> errorList = [
  ErrorModel(code: 1, message: 'کاربری یافت نشد'),
  ErrorModel(code: 2, message: 'نامکاربری یا رمزعبور اشتباه است'),
  ErrorModel(code: 3, message: 'کد تایید شما منقضی شده است'),
  ErrorModel(code: 4, message: 'کد تایید اشتباه است'),
  ErrorModel(code: 5, message: 'رمزعبور ضعیف است'),
  ErrorModel(code: 7, message: 'خطا در اتصال به درگاه پرداخت'),
  ErrorModel(code: 8, message: 'پرداخت ناموفق'),
  ErrorModel(code: 9, message: 'تصویر الزامی است'),
  ErrorModel(code: 10, message: 'سایز عکس زیاد است'),
  ErrorModel(code: 11, message: 'فرمت عکس اشتباه است'),
  ErrorModel(code: 14, message: 'سازمان یافت نشد'),
  ErrorModel(code: 15, message: 'قرارداد پیدا نشد'),
  ErrorModel(code: 16, message: 'اسکوتر در سفر است'),
  ErrorModel(code: 17, message: 'اسکوتر در سفر نیست'),
  ErrorModel(code: 18, message: 'کاربر غیرفعال است'),
  ErrorModel(code: 19, message: 'کاربر در سفر است'),
  ErrorModel(code: 20, message: 'کاربر در سفر نیست'),
  ErrorModel(code: 21, message: 'موقعیت یافت نشد'),
  ErrorModel(code: 22, message: 'فراموش شده'),
  ErrorModel(code: 23, message: 'اسکوتر درحال حرکت را نمیتوانید حذف کنید'),
  ErrorModel(code: 24, message: 'شناسه گزارش نامعتبر است'),
  ErrorModel(code: 25, message: 'کاربر قبلا ثبت شده است'),
  ErrorModel(code: 27, message: 'اسکوتر یافت نشد'),
  ErrorModel(code: 28, message: 'کاربر بدهی دارد'),
  ErrorModel(code: 29, message: 'اسکوتر در محدوده نیست'),
  ErrorModel(code: 30, message: 'عدم موفقیت در خاتمه دادن کاربر'),
  ErrorModel(code: 31, message: 'گزارش تخلیه ثبت شده است'),
];